APPTS 9.2.0 release note
Axway/platform-management-docs pull request #55
Opened 2022-02-10 21:34 UTC by pkclark

Thank you for your contribution to the Platform-Management-Docs repo.

## Describe the changes

Enter a brief description of your changes here to communicate to the maintainers what you changed and why.

## Checklist for contributors

Before submitting this PR, please make sure:

* [x] You have signed the [Axway CLA](https://cla.axway.com/)
* [x] You have verified the technical accuracy of your change
* [x] You have verified that your change does not expose any sensitive information (passwords, keys, etc.)

_Put an x in the boxes that apply. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your change._

## Checklist for approvers

_This section is to be filled out by project maintainers only._

Before approving this PR, please make sure it:

* [ ] Does not have conflicts with the base branch
* [ ] Is clear and complete
* [ ] Is believed to be accurate (technical accuracy to be checked with an SME for PRs originating from outside R&D)
* [ ] Follows [Axway style](https://techweb.axway.com/confluence/display/RIE/Style+guide)
* [ ] Does not contain typos, grammatical errors, etc.
* [ ] Does not expose any sensitive information
* [ ] Passes the Markdown linter rules (automated via CI check)
* [ ] Does not contain broken links

## Checklist for mergers

_This section is to be filled out by project maintainers only._

Before merging this PR, please make sure:

* [ ] You have applied a production label if this needs a manual push to Zoomin
* [ ] You have added it to the correct GitHub project
* [ ] You have added a new collection to Netlify CMS config (static/admin/config.js) if required (new doc sections)
* [ ] You have updated the Zoomin classification file if required (new folder of topics>

2022-02-10 22:09 UTC, sallylanda6 requested changes
See changes.

2022-02-10 22:09 UTC, sallylanda6 commented on content/en/docs/release_notes/09_02_00_relnotes.md
> +* Corrected an oudated _Connecting Environements_ documentation link on the _Platform Home_ Getting Started section.
```suggestion
* Corrected an outdated _Connecting Environments_ documentation link on the _Platform Home_ Getting Started section.
```

2022-02-10 22:09 UTC, sallylanda6 commented on content/en/docs/release_notes/09_02_00_relnotes.md
> +* Added a _Devices_ view in the _Account_ section for users using **Amplify Platform** for authentication allowing authorized devices to be viewed and managed.
```suggestion
* Added a _Devices_ view in the _Account_ section for users using **{{% variables/platform_prod_name %}}** for authentication allowing authorized devices to be viewed and managed.
```

2022-02-10 22:09 UTC, sallylanda6 commented on content/en/docs/release_notes/09_02_00_relnotes.md
> +* Added a _Devices_ view in the _Account_ section for users using **Amplify Platform** for authentication allowing authorized devices to be viewed and managed.
product variable changes it to Amplify platform

2022-02-11 00:20 UTC, pkclark commented on content/en/docs/release_notes/09_02_00_relnotes.md
> +* Added a _Devices_ view in the _Account_ section for users using **Amplify Platform** for authentication allowing authorized devices to be viewed and managed.
TIL those existed.

2022-02-11 00:22 UTC, pkclark commented
Suggestions merged.

2022-02-11 14:55 UTC, merged